trigger:
- main

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: CmdLine@2
  inputs:
    script: |
      wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
      tar -xzf apache-jmeter-5.6.3.tgz
      export PATH=$PATH:$(pwd)/apache-jmeter-5.6.3/bin
      
      # jmeter -n -t create_intent.jmx -l create_intent.jtl -e -o create_intent
       jmeter -n -t get_intents.jmx -l get_intents.jtl -e -o get_intents
       jmeter -n -t get_intent_by_id.jmx -l get_intent_by_id.jtl -e -o get_intent_by_id
      # jmeter -n -t kitchen_closure_automation.jmx -l kitchen_closure_automation.jtl -e -o kitchen_closure_automation
      # jmeter -n -t kitchen_normalization.jmx -l kitchen_normalization.jtl -e -o kitchen_normalization
      # jmeter -n -t network_alert.jmx -l network_alert.jtl -e -o network_alert
      # jmeter -n -t pause_online_ordering.jmx -l pause_online_ordering.jtl -e -o pause_online_ordering
      # jmeter -n -t thumbs_up_thumbs_down.jmx -l thumbs_up_thumbs_down.jtl -e -o thumbs_up_thumbs_down
      # jmeter -n -t toast_printer_down.jmx -l toast_printer_down.jtl -e -o toast_printer_down
      # jmeter -n -t intent_classifier.jmx -l intent_classifier.jtl -e -o intent_classifier

    workingDirectory: '$(System.DefaultWorkingDirectory)/jmeter_perfomance_testing'
  displayName: 'Install JMeter'

#- task: publishhtmlreport@1
#  inputs:
#    htmlType: 'Jmeter'
#    JmeterReportsPath: '$(System.DefaultWorkingDirectory)/jmeter_perfomance_testing/create_intent'

- task: publishhtmlreport@1
  inputs:
    htmlType: 'Jmeter'
    JmeterReportsPath: '$(System.DefaultWorkingDirectory)/jmeter_perfomance_testing/get_intents'

- task: publishhtmlreport@1
  inputs:
    htmlType: 'Jmeter'
    JmeterReportsPath: '$(System.DefaultWorkingDirectory)/jmeter_perfomance_testing/get_intent_by_id'

#- task: publishhtmlreport@1
#  inputs:
#    htmlType: 'Jmeter'
#    JmeterReportsPath: '$(System.DefaultWorkingDirectory)/jmeter_perfomance_testing/intent_classifier'

#- task: publishhtmlreport@1
#  inputs:
#    htmlType: 'Jmeter'
#    JmeterReportsPath: '$(System.DefaultWorkingDirectory)/jmeter_perfomance_testing/kitchen_closure_automation'

#- task: publishhtmlreport@1
#  inputs:
#    htmlType: 'Jmeter'
#    JmeterReportsPath: '$(System.DefaultWorkingDirectory)/jmeter_perfomance_testing/kitchen_normalization'

#- task: publishhtmlreport@1
#  inputs:
#    htmlType: 'Jmeter'
#    JmeterReportsPath: '$(System.DefaultWorkingDirectory)/jmeter_perfomance_testing/network_alert'

#- task: publishhtmlreport@1
#  inputs:
#    htmlType: 'Jmeter'
#    JmeterReportsPath: '$(System.DefaultWorkingDirectory)/jmeter_perfomance_testing/pause_online_ordering'

#- task: publishhtmlreport@1
#  inputs:
#    htmlType: 'Jmeter'
#    JmeterReportsPath: '$(System.DefaultWorkingDirectory)/jmeter_perfomance_testing/thumbs_up_thumbs_down'

#- task: publishhtmlreport@1
#  inputs:
#    htmlType: 'Jmeter'
#    JmeterReportsPath: '$(System.DefaultWorkingDirectory)/jmeter_perfomance_testing/toast_printer_down'
